import { appendFileSync, readFileSync } from "node:fs";

import { run as runConformance } from "./run.js";
import { toMarkdown } from "./format.js";
import type { ConformanceReport } from "./types.js";

export interface RunnerEnv {
  inputs: Record<string, string | undefined>;
  GITHUB_OUTPUT?: string;
  GITHUB_EVENT_NAME?: string;
  GITHUB_REPOSITORY?: string;
  GITHUB_EVENT_PATH?: string;
  readFile?: (path: string) => string;
  /** Inject a custom run() for tests; defaults to the vendored library. */
  runConformance?: (root: string, opts: { failOnUnknown?: boolean; skip?: string[] }) => ConformanceReport;
  postComment?: (args: { token: string; repo: string; issueNumber: number; body: string }) => Promise<void>;
  write?: (line: string) => void;
}

export interface RunnerResult {
  exitCode: 0 | 1;
  report: ConformanceReport;
  commentPosted: boolean;
  reason?: string;
}

export async function run(env: RunnerEnv): Promise<RunnerResult> {
  const dir = required(env.inputs, "dir");
  const commentOnPr = env.inputs.comment_on_pr ?? "auto";
  const failOnHigh = (env.inputs.fail_on_high ?? "true").toLowerCase() !== "false";
  const failOnUnknown = (env.inputs.fail_on_unknown ?? "true").toLowerCase() !== "false";
  const skipRaw = env.inputs.skip ?? "";
  const skip = skipRaw.split(",").map((s) => s.trim()).filter((s) => s.length > 0);
  const token = env.inputs.github_token ?? "";

  const read = env.readFile ?? ((p) => readFileSync(p, "utf8"));
  const write = env.write ?? ((line) => process.stdout.write(`${line}\n`));
  const conform = env.runConformance ?? ((root, opts) => runConformance(root, opts));

  const report = conform(dir, { failOnUnknown, skip });
  const markdown = toMarkdown(report);
  const highCount = report.findings.filter((f) => f.severity === "high").length;

  setOutput(env, "total-files", String(report.files));
  setOutput(env, "high-findings", String(highCount));
  setOutput(env, "conformant-docs", String(report.docs.filter((d) => d.structurallyConformant).length));
  setOutput(env, "unknown-docs", String(report.findings.filter((f) => f.code === "unknown-protocol").length));

  write(`\n${markdown}\n`);

  const isPullRequest = env.GITHUB_EVENT_NAME === "pull_request";
  const wantsComment = commentOnPr === "true" || (commentOnPr === "auto" && isPullRequest);
  let commentPosted = false;
  let reason: string | undefined;

  if (wantsComment) {
    if (!token) {
      reason = "no github-token provided";
    } else if (!env.GITHUB_EVENT_PATH) {
      reason = "no GITHUB_EVENT_PATH";
    } else if (!env.GITHUB_REPOSITORY) {
      reason = "no GITHUB_REPOSITORY";
    } else {
      const event = JSON.parse(read(env.GITHUB_EVENT_PATH)) as { number?: number; pull_request?: { number?: number } };
      const issueNumber = event.number ?? event.pull_request?.number;
      if (!issueNumber) {
        reason = "no PR number in event payload";
      } else {
        const body = `${markdown}\n\n_Generated by [kg-suite-conformance-runner-action](https://github.com/mizcausevic-dev/kg-suite-conformance-runner-action)._`;
        const poster = env.postComment ?? defaultPostComment;
        await poster({ token, repo: env.GITHUB_REPOSITORY, issueNumber, body });
        commentPosted = true;
      }
    }
  }

  if (failOnHigh && highCount > 0) {
    write(`::error::Suite conformance failed: ${highCount} high-severity finding(s).`);
    return { exitCode: 1, report, commentPosted, reason };
  }

  return { exitCode: 0, report, commentPosted, reason };
}

function required(inputs: Record<string, string | undefined>, name: string): string {
  const v = inputs[name];
  if (!v || v.length === 0) throw new Error(`input "${name}" is required`);
  return v;
}

function setOutput(env: RunnerEnv, key: string, value: string): void {
  if (env.GITHUB_OUTPUT) appendFileSync(env.GITHUB_OUTPUT, `${key}=${value}\n`);
}

async function defaultPostComment(args: { token: string; repo: string; issueNumber: number; body: string }): Promise<void> {
  const r = await fetch(`https://api.github.com/repos/${args.repo}/issues/${args.issueNumber}/comments`, {
    method: "POST",
    headers: {
      Accept: "application/vnd.github+json",
      Authorization: `Bearer ${args.token}`,
      "X-GitHub-Api-Version": "2022-11-28"
    },
    body: JSON.stringify({ body: args.body })
  });
  if (!r.ok) throw new Error(`GitHub API comment failed: ${r.status} ${await r.text()}`);
}
